SET FOREIGN_KEY_CHECKS = 0;
DROP TABLE IF EXISTS users;
DROP TABLE IF EXISTS user_access;
DROP TABLE IF EXISTS vehicles;
DROP TABLE IF EXISTS roles;
DROP TABLE IF EXISTS favourites;
SET FOREIGN_KEY_CHECKS = 1;